version: '3'
services:
  go-gin-container:
    build:
      context: .
      dockerfile: ./web-server/Dockerfile
    container_name: go-gin-app
    volumes:
      - ./go-app:/app
    ports:
      - "8080:8080"
    working_dir: /app
    command: go run main.go # Replace with your Go application entry point

  node-angular-container:
    build:
      context: .                 # Use the current directory as the build context
      dockerfile: ./web-client/Dockerfile
    container_name: node-angular-app
    volumes:
      - ./angular-app:/app
    ports:
      - "4200:4200"
      - "49153:49153" # For live-reload (optional)
    working_dir: /app
    command: ng serve
